name: "ismark_final_v3_10"
root_dir: "./output"
gpus: [1]
batch_size: 24
num_workers: 24
max_epochs: 2000
find_unused_parameters: false
ckpt_path: null #"/home/light_sun/workspace/inrsteg/output/INR_STEG_v11/lightning_logs/version_5/checkpoints/ckpt-epoch=09-val_loss=0.1014.ckpt"
lr: 0.001
n_val_epoch: 5
seed: 42

img_size: 128
msg_len: 30
feat_dim: 256
hidden_dim: 128
coord_map_dim: 32
decoder_blocks: 2
min_scale: 0.1

use_bg: true

# 好像没啥用了
use_fold: true
cache: false
use_global: false

tunable_decoder: true
fixed_psnr: 35
inject_rgb: true
noised: true

w_msg: 6
w_img: 1