name: "ismark_v6"
root_dir: "./output"
gpus: [2, 3]
batch_size: 32
num_workers: 32
max_epochs: 20000
find_unused_parameters: false
ckpt_path: "/home/light_sun/workspace/inrmark_2/inrsteg-final_v1/output/ismark_v6/lightning_logs/version_8/checkpoints/ckpt-epoch=239-val_loss=0.0125.ckpt"
lr: 0.001
n_val_epoch: 5
seed: 42

img_size: 128
msg_len: 30
feat_dim: 256
hidden_dim: 128
coord_map_dim: 32
decoder_blocks: 2
min_scale: 0.0 # 1

use_bg: true

# 好像没啥用了
use_fold: true
cache: false
use_global: false


use_cell: false # 不能加，加了就会导致不同尺度下解码不同了
tunable_decoder: true
fixed_psnr: 36
inject_rgb: true
noised: true
use_jnd: true
alpha: 0.02 # 0.02大概PSNR在35左右

w_msg: 2
w_img: 1
w_lpips: 0.